/**:
  ros__parameters:
    points:
      - x: 0.98   
        y: 0.16   #扫描第一个二维码和弯道起点
      - x: 0.93
        y: 5.30   #扫描箭头点
      - x: 0.0
        y: 5.52   #箭头旁的石板路起点
      - x: 2.0
        y: 5.52   #箭头旁的斜坡起点
      - x: 0
        y: 15     #二维码旁石板路后的拐弯点
      - x: 2
        y: 15     #二维码旁斜坡后的拐弯点
      - x: 1
        y: 15     #第二个二维码扫描点
      - x: 0
        y: 15.8   #B库1
      - x: 2
        y: 15.8   #B库2
      - x: 1.86
        y: -1.05  #A库1
      - x: -0.21
        y: -1.05  #A库2